test(vitest): remove unnecessary setup script
It doesn't seem to be necessary and was causing some errors when running
tests with the updated Vitest dependencies:

```
 FAIL  app/utils/general.test.ts [ app/utils/general.test.ts ]
Error: Missing "./extend-expect" specifier in "@testing-library/jest-dom" package
 ❯ e node_modules/.pnpm/vite@4.4.9_@types+node@18.18.1/node_modules/vite/dist/node/chunks/dep-df561101.js:21420:25
 ❯ n node_modules/.pnpm/vite@4.4.9_@types+node@18.18.1/node_modules/vite/dist/node/chunks/dep-df561101.js:21420:627
 ❯ o node_modules/.pnpm/vite@4.4.9_@types+node@18.18.1/node_modules/vite/dist/node/chunks/dep-df561101.js:21420:1297
 ❯ resolveExportsOrImports node_modules/.pnpm/vite@4.4.9_@types+node@18.18.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28712:20
 ❯ resolveDeepImport node_modules/.pnpm/vite@4.4.9_@types+node@18.18.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28731:31
 ❯ tryNodeResolve node_modules/.pnpm/vite@4.4.9_@types+node@18.18.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28419:20
 ❯ Context.resolveId node_modules/.pnpm/vite@4.4.9_@types+node@18.18.1/node_modules/vite/dist/node/chunks/dep-df561101.js:28180:28
 ❯ Object.resolveId node_modules/.pnpm/vite@4.4.9_@types+node@18.18.1/node_modules/vite/dist/node/chunks/dep-df561101.js:44207:32
 ❯ TransformContext.resolve node_modules/.pnpm/vite@4.4.9_@types+node@18.18.1/node_modules/vite/dist/node/chunks/dep-df561101.js:43923:23

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

 Test Files  1 failed (1)
      Tests  no tests
   Start at  21:39:51
   Duration  323ms (transform 22ms, setup 0ms, collect 0ms, tests 0ms, environment 93ms, prepare 90ms)

 FAIL  Tests failed. Watching for file changes...
       press h to show help, press q to quit
Cancelling test run. Press CTRL+c again to exit forcefully.
```